---
# Shutdown or Start all VMs on a vCenter (only for demo)
- hosts: all
  #Variables for vCenter and VMs
  vars:
    vcenter_ip: ""
    vcenter_username: ""
    vcenter_password: ""
    vm_name: ""
    state: ""
    force: ""
    
  tasks:
    - name: Set {{ state }} of virtuals machines
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name : "{{ item }}"
        state: "{{ state }}"
        force: "{{ force }}"
      with_items: "{{ vm_name }}"
      delegate_to: localhost
